apiVersion: v1
kind: Secret
metadata:
  name: restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: "__REPO_URL__" # e.g. "s3:http://minio.minio.svc.cluster.local:9000/my-bucket/pacman"
  RESTIC_PASSWORD: "__REPLACE_ME_WITH_WHATEVER_YOU_LIKE__"
  AWS_ACCESS_KEY_ID: "__ACCESS_KEY_ID__" # e.g. "access"
  AWS_SECRET_ACCESS_KEY: "__SECRET_ACCESS_KEY__" # e.g. "password"
