apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "restic-secret"
spec:
  secretStoreRef:
    name: tflow-cluster-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: "restic-secret"
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
    template:
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}/pacman-backup"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: tflow-restic-secret

