resources:
- mongo-pvc.yaml
- mongo-deployment.yaml
- mongo-service.yaml
- pacman-deployment.yaml
- pacman-service.yaml
- pacman-route.yaml
- replicationsource.yaml
- replicationdestination.yaml
- external-secret-restic-secret.yaml
