apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: repl-source
spec:
  sourcePVC: mongo-storage
  trigger:
    schedule: "*/20 * * * *"
  restic:
    pruneIntervalDays: 1
    repository: restic-secret
    retain:
      hourly: 3
      daily: 2
      monthly: 1
    copyMethod: Snapshot
    cacheCapacity: 1Gi
