apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    appname: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: busybox
  template:
    metadata:
      labels:
        appname: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'while true; do echo Mon May 13 16:05:44 EDT 2024 | tee -a /mnt/test/outfile; sync; sleep 10; done']
        volumeMounts:
        - name: mypvc
          mountPath: /mnt/test
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: test-pvc
          readOnly: false
